import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdir, readFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';

const { chromium } = await import(process.env.PLAYWRIGHT_MODULE_PATH ? pathToFileURL(process.env.PLAYWRIGHT_MODULE_PATH).href : 'playwright');
const server = spawn(process.execPath, ['tools/dev-server.mjs'], { env: { ...process.env, PORT: '0' }, stdio: ['ignore', 'pipe', 'pipe'] });
const url = await new Promise((resolve, reject) => {
  const timeout = setTimeout(() => reject(new Error('Test server did not start')), 10000);
  server.stdout.on('data', data => { const match = String(data).match(/http:\/\/localhost:\d+\//); if (match) { clearTimeout(timeout); resolve(match[0]); } });
  server.on('error', reject);
  server.stderr.on('data', data => console.error(String(data)));
});
let browser;
const checks = [];
const check = (name, value) => { assert.ok(value, name); checks.push(name); console.log(`PASS ${name}`); };

try {
  browser = await chromium.launch({ headless: true, ...(process.env.PLAYWRIGHT_CHANNEL ? { channel: process.env.PLAYWRIGHT_CHANNEL } : {}) });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => { errors.push(error.message); console.error('Browser error:', error.message); });
  page.on('dialog', dialog => dialog.accept());
  await page.goto(url, { waitUntil: 'domcontentloaded' });
  await page.locator('#btn-login-local').click();
  await page.locator('#app-view').waitFor({ state: 'visible' });
  check('explicit device-only sign-in', await page.locator('#view-dashboard').isVisible());
  check('real auth disabled until configured', await page.locator('#btn-login-google').isDisabled());
  await page.locator('[data-view="pantry"]').click();
  await page.locator('#pantry-ingredient-input').fill('Tomato');
  await page.locator('#pantry-quantity-input').fill('200');
  await page.locator('#pantry-unit-input').selectOption('g');
  await page.locator('#pantry-category-input').selectOption('Vegetables');
  await page.locator('#pantry-add-btn').click();
  check('ingredient quantity/unit/category', (await page.locator('#pantry-manager-tags').innerText()).includes('200 g'));
  await page.locator('#pantry-manager-tags [data-qty="1"]').click();
  check('quantity controls', (await page.locator('#pantry-manager-tags').innerText()).includes('201 g'));
  await page.locator('[data-view="ai-generator"]').click();
  check('explore remains hidden initially', !(await page.locator('#recipe-explore-panel').isVisible()));
  await page.locator('#recipe-title-input').fill('Browser Test Soup');
  await page.locator('#recipe-tags-input').fill('Vegan');
  await page.locator('#recipe-cook-count-input').selectOption('2');
  await page.locator('.recipe-ingredient-name').first().fill('Tomato');
  await page.locator('.recipe-ingredient-amount').first().fill('100');
  await page.locator('.recipe-ingredient-unit').first().selectOption('g');
  await page.locator('.recipe-step-item').first().fill('Tomato');
  await page.locator('.recipe-step-action').first().fill('Chop on cutting board');
  await page.locator('.recipe-step-duration').first().fill('1');
  await page.locator('.recipe-step-type').first().selectOption('Prep');
  await page.locator('#recipe-add-step-row').click();
  await page.locator('.recipe-step-item').nth(1).fill('Tomato');
  await page.locator('.recipe-step-action').nth(1).fill('Simmer in pot');
  await page.locator('.recipe-step-duration').nth(1).fill('1');
  await page.locator('.recipe-step-cook').nth(1).selectOption('Cook 2');
  check('automatic prep/cook totals', await page.locator('#recipe-prep-input').inputValue() === '1' && await page.locator('#recipe-cook-time-input').inputValue() === '1');
  await page.locator('#custom-recipe-form button[type="submit"]').click();
  await page.locator('#recipe-explore-toggle-btn').click();
  await page.locator('#recipe-search').fill('Browser Test Soup');
  await page.locator('#explore-recipes-grid .recipe-card').waitFor();
  check('saved custom recipe in Explore', await page.locator('#explore-recipes-grid .recipe-card').count() === 1);
  await page.locator('#explore-recipes-grid .recipe-favorite').click();
  await page.reload({ waitUntil: 'domcontentloaded' });
  await page.locator('[data-view="ai-generator"]').click();
  await page.locator('#recipe-explore-toggle-btn').click();
  await page.locator('#recipe-search').fill('Browser Test Soup');
  check('liked recipes survive reload', await page.locator('#explore-recipes-grid .recipe-favorite').getAttribute('aria-pressed') === 'true');
  await page.locator('#recipe-export-btn').click();
  await page.getByText('Browser Test Soup (Dinner)', { exact: true }).locator('..').locator('input').check();
  const [download] = await Promise.all([page.waitForEvent('download'), page.locator('#recipe-export-confirm-btn').click()]);
  const exported = JSON.parse(await readFile(await download.path(), 'utf8'));
  check('selective single-recipe export', exported.recipes.length === 1 && exported.recipes[0].title === 'Browser Test Soup');
  await page.locator('#recipe-import-file').setInputFiles({ name: 'recipes.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(exported)) });
  check('duplicate imports do not duplicate recipes', await page.evaluate(async () => (await import('/modules/state.js')).STATE.customRecipes.length) === 1);
  const cookDialogs = [];
  page.on('dialog', dialog => cookDialogs.push(dialog.message()));
  await page.locator('#explore-recipes-grid .recipe-card').click();
  await page.locator('#modal-btn-cook').click();
  check('cook dialog defaults to keeping pantry unchanged', await page.locator('#cook-meal-modal').isVisible() && await page.locator('input[name="cook-pantry-mode"][value="keep"]').isChecked());
  check('stocked recipe has no shortage warning', !(await page.locator('#cook-meal-shortages').isVisible()));
  await page.locator('#cook-meal-confirm-btn').click();
  check('default cooking preserves pantry quantity', await page.evaluate(async () => (await import('/modules/state.js')).STATE.pantry.find(item => item.name === 'Tomato')?.quantity === 201));
  check('cooking shows themed notification', (await page.locator('#cook-meal-toast-message').innerText()).includes('not changed'));
  await page.locator('#cook-meal-toast-close').click();
  await page.evaluate(async () => {
    const { STATE } = await import('/modules/state.js');
    STATE.pantry.find(item => item.name === 'Tomato').quantity = 50;
    (await import('/modules/storage.js')).saveStateToStorage();
  });
  await page.locator('#explore-recipes-grid .recipe-card').click();
  await page.locator('#modal-btn-cook').click();
  check('shortage appears in themed cook dialog', (await page.locator('#cook-meal-shortage-list').innerText()).includes('Tomato: need 100 g, have 50 g'));
  check('keeping pantry remains default for a new meal', await page.locator('input[name="cook-pantry-mode"][value="keep"]').isChecked());
  await page.setViewportSize({ width: 390, height: 844 });
  check('cook dialog fits phone viewport', await page.evaluate(() => {
    const rect = document.querySelector('.cook-meal-dialog').getBoundingClientRect();
    return rect.left >= 0 && rect.right <= innerWidth && rect.top >= 0 && rect.bottom <= innerHeight;
  }));
  await mkdir('output', { recursive: true });
  await page.screenshot({ path: 'output/cook-meal-mobile.png', animations: 'disabled' });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.keyboard.press('Escape');
  check('Escape cancels cooking without changing pantry', !(await page.locator('#cook-meal-modal').isVisible()) && await page.evaluate(async () => (await import('/modules/state.js')).STATE.pantry.find(item => item.name === 'Tomato')?.quantity === 50));
  await page.locator('#modal-btn-cook').click();
  await page.locator('input[name="cook-pantry-mode"][value="deduct"]').check();
  await page.locator('#cook-meal-confirm-btn').click();
  check('explicit deduction consumes only available pantry stock', await page.evaluate(async () => !(await import('/modules/state.js')).STATE.pantry.some(item => item.name === 'Tomato')));
  check('cook flow avoids native browser dialogs', cookDialogs.length === 0);
  await page.locator('#btn-profile').click();
  await page.locator('#profile-name-input').fill('Test Chef');
  await page.locator('#profile-diet-input').selectOption('Vegan');
  await page.locator('input[name="profile-experience"][value="Beginner"]').check();
  await page.locator('#profile-mute-audio-input').check();
  await page.locator('#profile-save-btn').click();
  check('saving profile retains current view', await page.locator('#view-ai-generator').isVisible());
  check('diet filters recipes', await page.evaluate(async () => (await import('/modules/recipe-domain.js')).getVisibleRecipes().every(recipe => recipe.tags.includes('Vegan'))));
  await page.locator('[data-view="play"]').click();
  await page.locator('#play-recipe-select').selectOption({ label: '[Dinner] Browser Test Soup' });
  await page.locator('#play-recipe-start-btn').click();
  check('parallel Cook 1/Cook 2 boards', await page.locator('#play-col-cook1 .play-step-card').count() === 1 && await page.locator('#play-col-cook2 .play-step-card').count() === 1);
  check('experience multiplier applied to Play Recipe', await page.evaluate(async () => (await import('/modules/state.js')).RUNTIME.playSession.running['Cook 2'].duration) === 120);
  await page.evaluate(async () => {
    const { RUNTIME } = await import('/modules/state.js');
    RUNTIME.playSession.running['Cook 1'].videoUrl = 'blob:test-placeholder';
    (await import('/modules/play-recipe.js')).renderPlayBoards();
    window.originalVideoNode = document.querySelector('#play-col-cook1 video');
    (await import('/modules/play-recipe.js')).runPlayRecipeTick();
  });
  check('timer redraw preserves video element', await page.evaluate(() => window.originalVideoNode === document.querySelector('#play-col-cook1 video')));
  await page.evaluate(async () => {
    const { RUNTIME } = await import('/modules/state.js');
    for (const step of Object.values(RUNTIME.playSession.running)) if (step) step.deadline = Date.now() - 1;
    (await import('/modules/play-recipe.js')).runPlayRecipeTick();
  });
  check('finished steps reach Completed', await page.locator('#play-col-completed .play-step-card').count() === 2);
  await page.locator('#play-recipe-reset-btn').click();
  check('reset clears boards', await page.locator('#play-col-completed .play-step-card').count() === 0);
  await page.locator('[data-view="planner"]').click();
  await page.locator('.planner-slot button').first().click();
  await page.locator('#select-meal-recipe-dropdown').selectOption(exported.recipes[0].id);
  await page.locator('#btn-select-meal-save').click();
  check('planner saves selected recipe', (await page.locator('.planner-day-card').first().innerText()).includes('Browser Test Soup'));
  await page.locator('.planner-slot button').first().click();
  await page.locator('#select-meal-recipe-dropdown').selectOption('');
  await page.locator('#btn-select-meal-save').click();
  check('clearing meal removes its schedule record', await page.evaluate(async () => Object.keys((await import('/modules/state.js')).STATE.scheduledMeals).length) === 0);

  const aiRequests = [];
  const providerRoute = /^https:\/\/(api\.openai\.com|api\.groq\.com|generativelanguage\.googleapis\.com)\//;
  await page.route(providerRoute, async route => {
    const request = route.request();
    const provider = request.url().includes('api.openai.com') ? 'openai' : request.url().includes('api.groq.com') ? 'groq' : 'gemini';
    const payload = request.postDataJSON();
    const schema = provider === 'gemini' ? payload.generationConfig.responseJsonSchema : payload.response_format.json_schema.schema;
    assert.equal(request.headers()[provider === 'gemini' ? 'x-goog-api-key' : 'authorization'], provider === 'gemini' ? 'gemini-test-key' : 'Bearer ' + (provider === 'groq' ? 'test-only-key' : 'openai-test-key'));
    aiRequests.push({ provider, schema });
    const result = schema.properties.calories
      ? { calories: 100, protein_g: 10, carbs_g: 20, fat_g: 2, fiber_g: 1 }
      : { title: 'Mock ' + provider + ' Rice', description: 'A simple rice dish', prepTime: 1, cookTime: 2, servings: 2, tags: ['Vegan'], category: 'Dinner', ingredients: [{ name: 'Rice', amount: 100, unit: 'g' }], steps: [{ item: 'Rice', action: 'Boil rice in pot', text: 'Boil rice in pot', duration: 120, stepType: 'Cook', cook: 'Cook 1' }] };
    const body = provider === 'gemini' ? { candidates: [{ finishReason: 'STOP', content: { parts: [{ text: JSON.stringify(result) }] } }] } : { choices: [{ finish_reason: 'stop', message: { content: JSON.stringify(result) } }] };
    await route.fulfill({ status: 200, contentType: 'application/json', headers: { 'Access-Control-Allow-Origin': '*' }, body: JSON.stringify(body) });
  });
  await page.locator('[data-view="ai-generator"]').click();
  if (!(await page.locator('#ai-provider-select').isVisible())) await page.locator('#view-ai-generator summary').filter({ hasText: 'Create with AI' }).click();
  for (const provider of ['openai', 'gemini', 'groq']) {
    await page.locator('#ai-provider-select').selectOption(provider);
    await page.locator('#ai-key-input').fill(provider === 'groq' ? 'test-only-key' : provider + '-test-key');
    await page.locator('#ai-key-save-btn').click();
    await page.locator('#btn-profile').click();
    check(provider + ' settings and saved key appear in Profile', await page.locator('#profile-ai-provider-select').inputValue() === provider && await page.locator('#profile-ai-key-input').inputValue() === (provider === 'groq' ? 'test-only-key' : provider + '-test-key'));
    await page.locator('#profile-ai-provider-select').selectOption(provider === 'groq' ? 'gemini' : 'groq');
    await page.locator('#profile-cancel-btn').click();
    check('cancelling Profile preserves ' + provider + ' selection', await page.locator('#ai-provider-select').inputValue() === provider);
    await page.locator('[data-view="pantry"]').click();
    await page.locator('#pantry-ingredient-input').fill(provider + ' Rice');
    await page.locator('#pantry-quantity-input').fill('100');
    await page.locator('#pantry-unit-input').selectOption('g');
    await page.locator('#pantry-category-input').selectOption('Grains');
    await page.locator('#pantry-add-btn').click();
    await page.waitForFunction(() => document.querySelector('#pantry-manager-tags .pantry-tag:last-child')?.textContent.includes('100 kcal'));
    check(provider + ' nutrition uses selected provider', aiRequests.at(-1).provider === provider && Boolean(aiRequests.at(-1).schema.properties.calories));
    const count = aiRequests.length;
    await page.locator('#pantry-manager-tags .pantry-tag').last().locator('[data-qty="1"]').click();
    check(provider + ' nutrition scales without another request', (await page.locator('#pantry-manager-tags').innerText()).includes('101 kcal') && aiRequests.length === count);
    await page.locator('[data-view="ai-generator"]').click();
    await page.locator('#ai-selectable-ingredients .selectable-tag').last().click();
    await page.locator('#ai-generate-btn').click();
    await page.locator('#ai-result-panel').waitFor({ state: 'visible' });
    check(provider + ' creates a structured recipe draft', await page.locator('#ai-recipe-title').innerText() === 'Mock ' + provider + ' Rice' && aiRequests.at(-1).provider === provider);
  }
  await page.unroute(providerRoute);
  await page.locator('#ai-provider-select').selectOption('openai');
  check('switching providers restores its own saved key', await page.locator('#ai-key-input').inputValue() === 'openai-test-key');
  await page.locator('#ai-key-input').fill('');
  await page.locator('#ai-key-save-btn').click();
  check('clearing one provider preserves other keys', await page.evaluate(async () => {
    const { getApiKey } = await import('/modules/storage.js');
    return !getApiKey('openai') && getApiKey('gemini') === 'gemini-test-key' && getApiKey('groq') === 'test-only-key';
  }));
  await page.locator('#btn-profile').click();
  await page.locator('#profile-ai-provider-select').selectOption('groq');
  await page.locator('#profile-save-btn').click();
  check('Profile save updates provider in AI settings', await page.locator('#ai-provider-select').inputValue() === 'groq' && await page.locator('#ai-key-input').inputValue() === 'test-only-key');
  check('both cook announcements queue and muting suppresses speech', await page.evaluate(async () => {
    const { STATE } = await import('/modules/state.js');
    const { speakPlayStep } = await import('/modules/play-media.js');
    const old = window.speechSynthesis.speak;
    const spoken = [];
    window.speechSynthesis.speak = utterance => spoken.push(utterance.text);
    STATE.user.mutePlayAudio = false;
    speakPlayStep({ cook: 'Cook 1', item: 'Tomato', action: 'Chop' });
    speakPlayStep({ cook: 'Cook 2', item: 'Rice', action: 'Boil' });
    STATE.user.mutePlayAudio = true;
    speakPlayStep({ cook: 'Cook 1', item: 'Soup', action: 'Stir' });
    window.speechSynthesis.speak = old;
    return spoken.length === 2 && spoken[0].includes('Cook 1') && spoken[1].includes('Cook 2');
  }));
  await page.locator('#btn-profile').click();
  const wav = Buffer.alloc(8044);
  wav.write('RIFF'); wav.writeUInt32LE(8036, 4); wav.write('WAVEfmt ', 8); wav.writeUInt32LE(16, 16);
  wav.writeUInt16LE(1, 20); wav.writeUInt16LE(1, 22); wav.writeUInt32LE(8000, 24); wav.writeUInt32LE(8000, 28);
  wav.writeUInt16LE(1, 32); wav.writeUInt16LE(8, 34); wav.write('data', 36); wav.writeUInt32LE(8000, 40); wav.fill(128, 44);
  await page.locator('#profile-music-file-input').setInputFiles({ name: 'test-music.wav', mimeType: 'audio/wav', buffer: wav });
  await page.waitForFunction(() => document.getElementById('profile-music-file-name').textContent === 'test-music.wav');
  await page.locator('#profile-save-btn').click();
  await page.reload({ waitUntil: 'domcontentloaded' });
  await page.locator('#btn-profile').click();
  await page.waitForFunction(() => document.getElementById('profile-music-file-name').textContent === 'test-music.wav');
  check('local music persists through reload', true);
  check('AI provider and key survive reload', await page.locator('#profile-ai-provider-select').inputValue() === 'groq' && await page.locator('#profile-ai-key-input').inputValue() === 'test-only-key');
  check('profile email is readonly', await page.locator('#profile-email-input').getAttribute('readonly') !== null);
  await page.locator('#profile-cancel-btn').click();
  await page.locator('[data-view="faq"]').click();
  check('FAQ available in app', await page.locator('#view-faq details').count() >= 6);
  await mkdir('output', { recursive: true });
  await page.locator('[data-view="play"]').click();
  await page.screenshot({ path: 'output/refactor-desktop.png', fullPage: true, animations: 'disabled' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.waitForTimeout(400);
  for (const view of ['dashboard', 'pantry', 'ai-generator', 'play', 'planner', 'faq']) {
    await page.evaluate(async view => (await import('/modules/navigation.js')).switchView(view), view);
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1);
    if (overflow) {
      console.log(await page.evaluate(() => [...document.querySelectorAll('body *')].filter(element => { const rect = element.getBoundingClientRect(); return rect.width > 0 && rect.right > window.innerWidth + 1 && getComputedStyle(element).display !== 'none'; }).slice(0, 12).map(element => ({ tag: element.tagName, id: element.id, class: element.className, width: element.getBoundingClientRect().width, right: element.getBoundingClientRect().right }))));
      await page.screenshot({ path: `output/overflow-${view}.png`, fullPage: true });
    }
    check(`mobile layout: ${view}`, !overflow);
  }
  await page.screenshot({ path: 'output/refactor-mobile.png', fullPage: true, animations: 'disabled' });
  await page.evaluate(() => navigator.serviceWorker.ready);
  await page.waitForFunction(() => Boolean(navigator.serviceWorker.controller));
  await context.setOffline(true);
  await page.reload({ waitUntil: 'domcontentloaded' });
  await page.locator('#app-view').waitFor({ state: 'visible' });
  check('offline module shell reloads', await page.locator('#sidebar-name').innerText() === 'Test Chef');
  await context.setOffline(false);
  await page.locator('#mobile-menu-toggle').click();
  await page.locator('#btn-logout').click();
  await page.locator('#auth-view').waitFor({ state: 'visible' });
  await page.locator('#btn-login-local').click();
  check('device-only logout retains recipes', await page.evaluate(async () => (await import('/modules/state.js')).STATE.customRecipes.length) === 1);
  check('stale account loads cannot overwrite a newer account', await page.evaluate(async () => {
    const { BackendAuthDB } = await import('/modules/backend-auth-db.js');
    const { applyAuthUser } = await import('/modules/auth.js');
    const { STATE } = await import('/modules/state.js');
    const { getApiKey } = await import('/modules/storage.js');
    const originalLoad = BackendAuthDB.loadUserState;
    const originalMigration = BackendAuthDB.needsMigration;
    let finishA;
    BackendAuthDB.loadUserState = uid => uid === 'account-a'
      ? new Promise(resolve => { finishA = resolve; })
      : Promise.resolve({ user: { name: 'Account B', email: 'untrusted-email' }, pantry: [{ id: 'b', name: 'Carrot', quantity: 1, unit: 'pcs' }], customRecipes: [], scheduledMeals: {} });
    BackendAuthDB.needsMigration = () => false;
    const pendingA = applyAuthUser({ uid: 'account-a', email: 'a@example.test' });
    await applyAuthUser({ uid: 'account-b', email: 'b@example.test' });
    finishA({ user: { name: 'Account A' }, pantry: [], customRecipes: [], scheduledMeals: {} });
    await pendingA;
    const isolated = STATE.user.email === 'b@example.test' && STATE.pantry[0].name === 'Carrot' && !getApiKey();
    BackendAuthDB.loadUserState = originalLoad;
    BackendAuthDB.needsMigration = originalMigration;
    await applyAuthUser(null);
    return isolated && STATE.customRecipes.length === 1 && getApiKey() === 'test-only-key';
  }));
  check('no uncaught browser errors', errors.length === 0);
  console.log(`${checks.length} browser checks passed.`);
} finally {
  await browser?.close();
  server.kill();
}
